поменяла названия переменных, поменяла название CommandBegin. Перенес…
XurmaKS/CsharpCalculator pull request #1
Opened 2022-03-30 13:26 UTC by XurmaKS

…ла метод в другой класс, добавила enum, добавила обертку для GetNumberForOperations

2022-04-03 15:07 UTC, WombatWithBeard requested changes

2022-04-03 15:07 UTC, WombatWithBeard commented on Calculator2.0/Calculations.cs
> +        public static Operations GettingANumberToSelectACommand()
на всякий случай, не критично сейчас, но артикли не используют в названия - ну типо никто не будет писать AnOptional когда можно Optional

2022-04-03 15:07 UTC, WombatWithBeard commented on Calculator2.0/EnteringNumbers.cs
> +        // public double[] GetTwoValuesForCalculations()
убирай закоменченное

2022-04-03 15:07 UTC, WombatWithBeard commented on Calculator2.0/AllMessage.cs
> +        {
у нас есть Enum мат.операций, давай тут сразу выводить все значения что есть в enum

2022-04-03 15:07 UTC, WombatWithBeard commented on Calculator2.0/Program.cs
> -                    enteringNumbers.commandBegin();
а теперь давай все это дело обернем в какой-нибудь class Data - и ты на основе него будешь все заполнять, и его везде прокидывать. 
То есть в классе будет
1. Тип операции
2. Множитель 
3. Тот класс с введенными числами
4. Результат.

2022-04-04 15:15 UTC, XurmaKS commented on Calculator2.0/AllMessage.cs
> +        {
+

2022-04-04 15:15 UTC, XurmaKS commented on Calculator2.0/EnteringNumbers.cs
> +        // public double[] GetTwoValuesForCalculations()
+

2022-04-06 12:03 UTC, XurmaKS commented on Calculator2.0/Program.cs
> -                    enteringNumbers.commandBegin();
+

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/Calculations.cs
> +                    return MathOperation.Addition(data.Entering.GetNumbersForCalculations());
если я правильно понял - то ты:
1. передаешь класс дата в калькулейт
2. вызываешь метод у вложенного класса в классе дата
3. КОТОРЫЙ ВОЗВРАЩАЕТ НОВЫЙ КЛАСС ДАТА
Найди логическую ошибку

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/Data.cs
> +        public EnteringNumbers Entering { get; set; } = new EnteringNumbers();
нахуй эту залупу отсюда

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/Program.cs
> +
заполнить data.numbers здесь, через статический метод статического класса EnteringNumbers

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/Calculations.cs
> +                    return MathOperation.Addition(data.Entering.GetNumbersForCalculations());
переделать на получение нормальных чисел

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/Calculations.cs
> +                    return MathOperation.Subtraction(data.Entering.GetNumbersForCalculations());
переделать на получение нормальных чисел

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/Calculations.cs
> +                    return MathOperation.Multiplication(data.Entering.GetNumbersForCalculations());
переделать на получение нормальных чисел

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/Calculations.cs
> +                    return MathOperation.Division(data.Entering.GetNumbersForCalculations());
переделать на получение нормальных чисел

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/Calculations.cs
> +        public static Dictionary<int, string> EnumList()
зачем это здесь?

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/EnteringNumbers.cs
> -
зачем закоменченный код? мы с прошлого раза решили что он не нужен

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/EnteringNumbers.cs
> +        public Data GetNumbersForCalculations()
метод который дословно называется "ПОЛУЧИТЬ ЧИСЛА ДЛЯ ВЫЧЕСЛЕНИЯ" - должен возвращать числа для вычесления, а не класс дата

2022-04-13 10:20 UTC, WombatWithBeard commented on Calculator2.0/MathOperation.cs
> +            double result = number.Numbers.OneNumber / number.Numbers.TwoNumber;
проверку на 0 выше

2022-04-13 16:56 UTC, XurmaKS commented on Calculator2.0/EnteringNumbers.cs
> -
сделано

2022-04-13 16:58 UTC, XurmaKS commented on Calculator2.0/MathOperation.cs
> +            double result = number.Numbers.OneNumber / number.Numbers.TwoNumber;
сделано

2022-04-13 17:28 UTC, XurmaKS commented on Calculator2.0/Calculations.cs
> +        public static Dictionary<int, string> EnumList()
сделано

2022-04-13 17:28 UTC, XurmaKS commented on Calculator2.0/Data.cs
> +        public EnteringNumbers Entering { get; set; } = new EnteringNumbers();
убрано

2022-04-17 08:54 UTC, XurmaKS commented on Calculator2.0/Program.cs
> +
сделано

2022-04-17 08:54 UTC, XurmaKS commented on Calculator2.0/EnteringNumbers.cs
> +        public Data GetNumbersForCalculations()
сделано

2022-04-17 08:54 UTC, XurmaKS commented on Calculator2.0/Calculations.cs
> +                    return MathOperation.Division(data.Entering.GetNumbersForCalculations());
сделано

2022-04-17 08:54 UTC, XurmaKS commented on Calculator2.0/Calculations.cs
> +                    return MathOperation.Subtraction(data.Entering.GetNumbersForCalculations());
сделано

2022-04-17 08:57 UTC, XurmaKS commented on Calculator2.0/Calculations.cs
> +                    return MathOperation.Addition(data.Entering.GetNumbersForCalculations());
сделано

2022-04-19 12:47 UTC, WombatWithBeard approved these changes

2022-04-19 12:47 UTC, WombatWithBeard commented on Calculator2.0/AllMessage.cs
>               Console.WriteLine(key.Key + " -> " + key.Value);
key.Key - Key.value :D
переименую лучше в operation, тогда будет operation.Key - operation.Value

2022-04-19 14:16 UTC, XurmaKS commented on Calculator2.0/AllMessage.cs
>               Console.WriteLine(key.Key + " -> " + key.Value);
сделано

2022-04-19 14:41 UTC, merged